# .readthedocs.yml
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2

mkdocs:
  configuration: mkdocs.yml
  fail_on_warning: false

python:
  version: 3.7
  install:
    - requirements: docs/requirements.txt

formats: all